worker_processes auto;

events {
    worker_connections 2048;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr info;

    upstream app_backend {
        server app-backend:8080;
        keepalive 32;
    }

    server {
        listen 443 ssl;
        server_name nginx-classic;

        ssl_protocols TLSv1.3;
        ssl_certificate /certs/server.crt;
        ssl_certificate_key /certs/server.key;
        ssl_ecdh_curve X25519;
        ssl_session_tickets off;
        ssl_session_cache off;

        add_header X-TFG-Environment "nginx-production-like" always;
        add_header X-TFG-TLS-Group "X25519" always;

        location / {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://app_backend;
        }
    }
}
