server {
    listen 8080;
    server_name app-backend;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/status {
        default_type application/json;
        return 200 '{"service":"critical-demo","status":"ok","backend":"internal-http"}';
    }
}
